In [8]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd


numpy merupakan library python yang digunakan untuk komputasi matriks.
matplotlib merupakan library untuk presentasi data berupa grafik atau plot.


In [10]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
print(x)

[['Roti' 44.0 20000.0]
 ['Pisang' 27.0 50000.0]
 ['Keju' 30.0 45000.0]
 ['Pisang' 38.0 25000.0]
 ['Keju' 40.0 nan]
 ['Roti' 35.0 15000.0]
 ['Pisang' nan 35000.0]
 ['Roti' 48.0 55000.0]
 ['Keju' 50.0 10000.0]
 ['Roti' 37.0 40000.0]]


In [13]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [18]:
print(x)

[['Roti' 44.0 20000.0]
 ['Pisang' 27.0 50000.0]
 ['Keju' 30.0 45000.0]
 ['Pisang' 38.0 25000.0]
 ['Keju' 40.0 32777.77777777778]
 ['Roti' 35.0 15000.0]
 ['Pisang' 38.77777777777778 35000.0]
 ['Roti' 48.0 55000.0]
 ['Keju' 50.0 10000.0]
 ['Roti' 37.0 40000.0]]


In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [24]:
print(x)

[[0.0 0.0 1.0 44.0 20000.0]
 [0.0 1.0 0.0 27.0 50000.0]
 [1.0 0.0 0.0 30.0 45000.0]
 [0.0 1.0 0.0 38.0 25000.0]
 [1.0 0.0 0.0 40.0 32777.77777777778]
 [0.0 0.0 1.0 35.0 15000.0]
 [0.0 1.0 0.0 38.77777777777778 35000.0]
 [0.0 0.0 1.0 48.0 55000.0]
 [1.0 0.0 0.0 50.0 10000.0]
 [0.0 0.0 1.0 37.0 40000.0]]


In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [26]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [28]:
print(x_train)

[[0.0 1.0 0.0 38.77777777777778 35000.0]
 [1.0 0.0 0.0 40.0 32777.77777777778]
 [0.0 0.0 1.0 44.0 20000.0]
 [0.0 1.0 0.0 38.0 25000.0]
 [0.0 1.0 0.0 27.0 50000.0]
 [0.0 0.0 1.0 48.0 55000.0]
 [1.0 0.0 0.0 50.0 10000.0]
 [0.0 0.0 1.0 35.0 15000.0]]


In [29]:
print(x_test)

[[1.0 0.0 0.0 30.0 45000.0]
 [0.0 0.0 1.0 37.0 40000.0]]


In [30]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [31]:
print(y_test)

[0 1]


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [36]:
print(x_train)

[[0.0 1.0 0.0 -0.19159184384578545 0.3096050863878049]
 [1.0 0.0 0.0 -0.014117293757057777 0.16173400035183857]
 [0.0 0.0 1.0 0.566708506533324 -0.6885247443549691]
 [0.0 1.0 0.0 -0.30453019390224867 -0.3558148007740445]
 [0.0 1.0 0.0 -1.9018011447007988 1.307734917130579]
 [0.0 0.0 1.0 1.1475343068237058 1.6404448607115036]
 [1.0 0.0 0.0 1.4379472069688968 -1.3539446315168184]
 [0.0 0.0 1.0 -0.7401495441200351 -1.0212346879358938]]


In [37]:
print(x_test)

[[1.0 0.0 0.0 -1.4661817944830124 0.9750249735496542]
 [0.0 0.0 1.0 -0.44973664397484414 0.6423150299687296]]
